'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Этот класс создан автоматически классом StronglyTypedResourceBuilder
'с помощью такого средства, как ResGen или Visual Studio.
'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
'с параметром /str или перестройте свой проект VS.
'''<summary>
'''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
Public Module Resources
    
    Private resourceMan As Global.System.Resources.ResourceManager
    
    Private resourceCulture As Global.System.Globalization.CultureInfo
    
    '''<summary>
    '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FullFeaturedMdiDemo.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
    '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property add_derived_table() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("add_derived_table", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property add_union_subquery() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("add_union_subquery", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property application_cascade() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("application_cascade", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property application_tile_horizontal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("application_tile_horizontal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property application_tile_vertical() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("application_tile_vertical", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property cancel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property connect() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("connect", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property copy_union_subquery() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("copy_union_subquery", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Public ReadOnly Property cut() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property database_save() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("database_save", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Public ReadOnly Property disk() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("disk", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property disk_plus() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("disk_plus", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property drive_disk() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("drive_disk", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Public ReadOnly Property folder_page() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_page", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Public ReadOnly Property help() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property new_object() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("new_object", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property page_copy() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("page_copy", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property page_paste() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("page_paste", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Public ReadOnly Property page_white() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("page_white", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Public ReadOnly Property query_properties() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("query_properties", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Module
