'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Этот класс создан автоматически классом StronglyTypedResourceBuilder
'с помощью такого средства, как ResGen или Visual Studio.
'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
'с параметром /str или перестройте свой проект VS.
'''<summary>
'''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FullFeaturedDemo.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
    '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property add_derived_table() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("add_derived_table", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property add_union_subquery() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("add_union_subquery", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Friend Shared ReadOnly Property App() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("App", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property application_cascade() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("application_cascade", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property application_tile_horizontal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("application_tile_horizontal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property application_tile_vertical() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("application_tile_vertical", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property cancel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property connect() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("connect", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property copy_union_subquery() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("copy_union_subquery", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Friend Shared ReadOnly Property cut() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property database_save() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("database_save", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Friend Shared ReadOnly Property disk() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("disk", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property disk_plus() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("disk_plus", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property drive_disk() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("drive_disk", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Friend Shared ReadOnly Property folder_page() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_page", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Friend Shared ReadOnly Property help() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property new_object() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("new_object", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property page_copy() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("page_copy", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property page_paste() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("page_paste", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
    '''</summary>
    Friend Shared ReadOnly Property page_white() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("page_white", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property query_properties() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("query_properties", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
