'*******************************************************************'
'       Active Query Builder Component Suite                        '
'                                                                   '
'       Copyright © 2006-2019 Active Database Software              '
'       ALL RIGHTS RESERVED                                         '
'                                                                   '
'       CONSULT THE LICENSE AGREEMENT FOR INFORMATION ON            '
'       RESTRICTIONS.                                               '
'*******************************************************************'

Imports System.Windows.Controls
Imports System.Windows.Media

Namespace AutoGeneratedProperties
	Friend Class GroupLabel
		Inherits TextBlock

		Public Sub New()
			Foreground = Brushes.CornflowerBlue

		End Sub
	End Class
End Namespace
