Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property add_derived_table() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("add_derived_table", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property add_union_subquery() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("add_union_subquery", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property application_cascade() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("application_cascade", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property application_tile_horizontal() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("application_tile_horizontal", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property application_tile_vertical() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("application_tile_vertical", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property cancel() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property copy_union_subquery() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("copy_union_subquery", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		''' </summary>
		Friend ReadOnly Property cut() As System.Drawing.Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Icon))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property database_save() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("database_save", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		''' </summary>
		Friend ReadOnly Property disk() As System.Drawing.Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("disk", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Icon))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property disk_plus() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("disk_plus", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property drive_disk() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("drive_disk", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		''' </summary>
		Friend ReadOnly Property folder_page() As System.Drawing.Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("folder_page", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Icon))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		''' </summary>
		Friend ReadOnly Property help() As System.Drawing.Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Icon))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property new_object() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("new_object", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property page_copy() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("page_copy", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property page_paste() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("page_paste", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		''' </summary>
		Friend ReadOnly Property page_white() As System.Drawing.Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("page_white", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Icon))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property query_properties() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("query_properties", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Module
End Namespace
