'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")>
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")>
		Public Property IsMaximized() As Boolean
			Get
				Return (DirectCast(Me("IsMaximized"), Boolean))
			End Get
			Set(value As Boolean)
				Me("IsMaximized") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
		Public Property Connections() As ConnectionList
			Get
				Return (DirectCast(Me("Connections"), ConnectionList))
			End Get
			Set(value As ConnectionList)
				Me("Connections") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("True")>
		Public Property CallUpgrade() As Boolean
			Get
				Return (DirectCast(Me("CallUpgrade"), Boolean))
			End Get
			Set(value As Boolean)
				Me("CallUpgrade") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("Auto")>
		Public Property Language() As String
			Get
				Return (DirectCast(Me("Language"), String))
			End Get
			Set(value As String)
				Me("Language") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
		Public Property XmlFiles() As ConnectionList
			Get
				Return (DirectCast(Me("XmlFiles"), ConnectionList))
			End Get
			Set(value As ConnectionList)
				Me("XmlFiles") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("")>
		Public Property Options() As String
			Get
				Return (DirectCast(Me("Options"), String))
			End Get
			Set(value As String)
				Me("Options") = value
			End Set
		End Property
	End Class
End Namespace
